site_name: My IT Journal
repo_url: "https://github.com/rosariolm/myjournal"
repo_name: "rosariolm/myjournal"
edit_uri: "edit/main/docs"

theme:
  icon:
    logo: fontawesome/solid/chalkboard-teacher
    repo: fontawesome/brands/git-alt
  name: material
  primary: indigo
  features:
    -navigation.expand
    -navigation.sections
    -navigation.tabs
    -navigation.top

nav:
  - Home: index.md
  - Tagesberichte: tberichte.md
  - Archiv: archiv.md
  - Wochenberichte:
      - "Git Befehlsreferenz": wberichte/w34_gitcheat.md
      - "MkDocs installieren": wberichte/w33_mkdocs.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date:
      enable_if_env: CI
  - git-revision-date-localized:


copyright: Copyright &copy; 2021 Laura Rosario
