site_name: My IT Journal
repo_url: "https://github.com/rosariolm/myjournal"
repo_name: "rosariolm/myjournal"
edit_uri: "edit/main/docs"

theme:
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - mavigation.top
  icon:
    logo: fontawesome/solid/chalkboard-teacher
    repo: fontawesome/brands/git-alt
    admonition:
      note: fontawesom/solid/sticky-note
      abstract: octicons/checklist-16
      info: octicons/info-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  name: material
  primary: indigo

nav:
  - Home: index.md
  - Tagesberichte: tberichte.md
  - Archiv: archiv.md
  - Wochenberichte:
      - "Link Aggregation": wberichte/w50_LinkAggregation.md
      - "VLAN hinzufügen": wberichte/w48_VlanHinzufuegen.md
      - "Switch Taggen und untaggen": wberichte/w47_SwitchTaganduntag.md
      - "Tag im Ethernet Frame": wberichte/w45_TagImEthernetFrame.md
      - "Gelerntes": wberichte/gelerntes.md
      - "Vagrant Befehle": wberichte/w40_vagrant.md
      - "git Q & A": wberichte/w37_gitQandA.md
      - "Workflow": wberichte/w36_workflow.md
      - "git Befehlsreferenz": wberichte/w34_gitcheat.md
      - "MkDocs installieren": wberichte/w33_mkdocs.md

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true


plugins:
  - git-revision-date:
      enabled_if_env: CI
  -search:
  - git-revision-date-localized:

copyright: Copyright &copy; 2021 Laura Marie Rosario
