site_name: My IT Journal
repo_url: "https://github.com/rosariolm/myjournal"
repo_name: "rosariolm/myjournal"
edit_uri: "edit/main/docs"

theme:
  features:
    - tabs
    - instant
    - content.tabs.link
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - mavigation.top
  icon:
    logo: material/library
    repo: fontawesome/brands/gitlab
    admonition:
      note: fontawesom/solid/sticky-note
      abstract: octicons/checklist-16
      info: octicons/info-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  name: material
  primary: indigo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk

nav:
  - Home: index.md
  - Tagesberichte: tberichte.md
  - Archiv:
      - "Februar2022": archiv/Februar2022.md
      - "Januar 2022": archiv/Januar2022.md
      - "Dezember 2021": archiv/Dezember2021.md
      - "November 2021": archiv/November2021.md
      - "Oktober 2021": archiv/Oktober2021.md
      - "September 2021": archiv/September2021.md
  - Wochenberichte:
      - "Autopilot Script Anpassung": wberichte/w8_AutoPilotScript.md
      - "Gerät bei Autopilot hinzufügen": wberichte/w7_AutoPilot.md
      - "PIN Deaktivierung in Intune": wberichte/w5_PIN.md
      - "Netzwerkadresse berechnen": wberichte/w4_NetzAdrBerechnen.md
      - "Link Aggregation": wberichte/w50_LinkAggregation.md
      - "VLAN hinzufügen": wberichte/w48_VlanHinzufuegen.md
      - "Switch Taggen und untaggen": wberichte/w47_SwitchTaganduntag.md
      - "Tag im Ethernet Frame": wberichte/w45_TagImEthernetFrame.md
      - "Gelerntes": wberichte/gelerntes.md
      - "Vagrant Befehle": wberichte/w40_vagrant.md
      - "git Q & A": wberichte/w37_gitQandA.md
      - "Workflow": wberichte/w36_workflow.md
      - "git Befehlsreferenz": wberichte/w34_gitcheat.md
      - "MkDocs installieren": wberichte/w33_mkdocs.md
  - Arbeitshefter:
      - "INF":
          - "Inhaltsverzeichnis": aberichte/inf/verzeichnis.md
          - "ISO/OSI Modell": aberichte/inf/IsoOsi.md
          - "Layer 1": aberichte/inf/layer1.md
          - "Layer 2": aberichte/inf/layer2.md
          - "Layer 3": aberichte/inf/layer3.md
          - "Praktische Arbeiten und Erfahrung": aberichte/inf/4.md

markdown_extensions:
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.critic
  - attr_list
  - md_in_html
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins:
  - git-revision-date:
      enabled_if_env: CI
  - search

copyright: Copyright &copy; 2022 Laura Marie Rosario
