site_name: My IT Journal
theme:
  name: material
  primary: indigo

nav:
  - Home: index.md
  - Tagesberichte: tberichte.md
  - Archiv: archiv.md
  - Wochenberichte: wberichte.md
  - Archiv: archiv2.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2021 Laura Rosario
